### ISSUE TITLE
Error when updating database

### ISSUE THREAD

**Issue by indrakaw** [sqlitebrowser/dio#5]
I already setup all the requirement on `config.toml` and able to pull a database.

An error occur when I update the database. I already perform `dio licence get all`.
```
2019/07/19 22:41:06 Errors when updating database licence:
2019/07/19 22:41:06 Post https://dbhub.io:5550/db_update: x509: certificate is valid for db4s.dbhub.io, not dbhub.io
Error when updating database licence
```

**Comment by justinclift** [comment]
Thanks @indrakaw.  I'm about to get some sleep, but will investigate this tomorrow. :smile:

**Comment by karim** [comment]
@justinclift I think you need to issue a new LE certificate for db4s.dbhub.io, or if you want to use the same certificate for both dbhub.io and db4s.dbhub.io you can do so also. More info here https://community.letsencrypt.org/t/can-i-use-letsencrypt-in-more-than-one-subdomain/16588.

**Comment by justinclift** [comment]
@indrakaw Checking things with `dio` just now, it's working ok when I try to do stuff with the remote server.  As an initial guess, maybe your DB4S client certificate has expired?

It's the file listed in the `cert` entry in the `~/.dio/config.toml` configuration file.  For example, on my system it's:

```
cert = '/home/jc/justinclift.cert.pem'
```

The way to check, is by running `openssl x509 -text` on it. eg:

```
$ openssl x509 -text -in /home/jc/justinclift.cert.pem| grep 'Not After'
            Not After : Mar 21 11:02:43 2020 GMT
```

If that's does seem to be the problem, just login to the DBHub.io website again, click the "Generate client certificate" button, and save it over the top of the old one.

If that's not the problem though... more investigation is needed. :wink:

@karim The db4s.dbhub.io server doesn't use Lets Encrypt.  We use our own Certificate Authority for all of our non-website pieces (on purpose).

**Comment by justinclift** [comment]
Ugh.  Found the problem.  It looks like the code for the `update` command is outdated.  It's still trying to use `/db_update`, which was for the original prototype API before adapting to DBHub.io.

Not sure how I missed that. :frowning:   It seems like mostly a left over command, that could probably be dropped.

To update the database license... instead use `dio commit`.  For example:

```
$ dio commit --licence CC0 2.5mb.sqlite
```

Then push the change to the remote server:

```
$ dio push 2.5mb.sqlite 
Pushing 1 commit for branch 'master' to https://dbhub.io:5550...
```

**Comment by justinclift** [comment]
Interestingly, doing that triggers some bugs.  Investigating...

**Comment by justinclift** [comment]
Fixed one bug.  Using the `--licence` option when the database hadn't been changed was failing the initial commit check.  (eg "Has the database been modified?")

Fixed in de721ac7b064190160bc708c334802069e620ceb.

There's one more bug to investigate.  Using `dio push` as per the above example is failing.  It's sending the commit data to the server, but the details aren't being generated in a matching fashion there.

Will investigate this tomorrow.  Way too sleepy atm.

Sorry for the delay @indrakaw.  As you can see, this is still fairly early stage code, getting the initial bugs worked out. :wink:

**Comment by karim** [comment]
> @karim The db4s.dbhub.io server doesn't use Lets Encrypt. We use our own Certificate Authority for all of our non-website pieces (on purpose).

I didn't know that, sorry.

I thought it was using Lets Encrypt because I tried to access https://db4s.dbhub.io/ (default port 443) using a browser and it returned dbhub.io LE certificate. It seems like you have a process listening on this port. Also http://db4s.dbhub.io/ (default port 80) is returning nginx test page. They should be disabled or redirected maybe?

**Comment by justinclift** [comment]
Oh, forgot about port 80 for the subdomain.  Both db4s.dbhub.io and dbhub.io are running in the same VM, with port 80 being set up for dbhub.io to bounce requests to https.

Ideally the db4s one should be in it's own VM, where port 80 isn't open.  I'll get to it... at some point.

Probably not too far off. :smile:

**Comment by pl77** [comment]
> There's one more bug to investigate. Using `dio push` as per the above example is failing. It's sending the commit data to the server, but the details aren't being generated in a matching fashion there.

I'm encountering this as well with the latest 3.1 version of dio.  I can pull and commit but as soon as I try to push the updated version to the server it responds:

```Pushing 1 commit for branch 'master' to https://db4s.dbhub.io...```
```Unexpected response from server, doesn't contain new commit ID.```

**Comment by justinclift** [comment]
Uh oh, that's not good.  I'm coming back to this stuff from taking some time off, so can look into this over the next few days.

@pl77 How urgent for you is this?  You should be able to use [DB Browser for SQLite](https://sqlitebrowser.org) in the meantime for a manual approach, which *might* be workable in the short term?

**Comment by pl77** [comment]
@justinclift No worries, I'm just playing with it for now so no rush whatsoever!  Figured it was something on my end but I tried a few times, blowing away the entire repo each time, tweaking my email, etc, and couldn't make it work.  I was hoping it was just an error on my part :D

**Comment by VinnyOG** [comment]
> > There's one more bug to investigate. Using `dio push` as per the above example is failing. It's sending the commit data to the server, but the details aren't being generated in a matching fashion there.
> 
> I'm encountering this as well with the latest 3.1 version of dio. I can pull and commit but as soon as I try to push the updated version to the server it responds:
> 
> `Pushing 1 commit for branch 'master' to https://db4s.dbhub.io...`
> `Unexpected response from server, doesn't contain new commit ID.`

I'm hitting the same issue. Is my best bet to hunt this down locally and spin up my own instance? Are there any plans on releasing a fix in the near future?

Thanks! I am very much enjoying dio and dbhub!

**Comment by justinclift** [comment]
Ahhhh.  It's on my rough ToDo list, but I've been busy with my new (main) job so haven't really been active with this stuff lately.

So, it'll get fixed "at some point" if no-one else figures out what the solution is.  In the meantime, if you're willing + able to spin up your own instance to investigate that would be *super* welcome! :smile:

**Comment by MKleusberg** [comment]
@VinnyOG Can you give it another try? I have tried to fix it on the server side, so you don't even need to fetch a new version of dio :smile:

**Comment by VinnyOG** [comment]
> @VinnyOG Can you give it another try? I have tried to fix it on the server side, so you don't even need to fetch a new version of dio 😄

@MKleusberg It worked! Thank you very much I appreciate it brother 😁

**Comment by justinclift** [comment]
That's awesome @MKleusberg!

**Comment by MKleusberg** [comment]
Awesome! I'm glad it is working :smile: I'll close this issue then.

@VinnyOG If you stumble upon any other issues when using DBHub.io, please let us know. It's still in early development and reports like this can make a big difference.

@pl77 If you're still around: The problem should be fixed. You can just try again without redownloading dio or changing anything on DBHub.io.
