### ISSUE TITLE
'dio list' with no databases fails with unmarshaling error

### ISSUE THREAD

**Issue by larsks** [sqlitebrowser/dio#9]
I just installed `dio`, and trying to run `dio list` results in:

```
Error retrieving database list: 'json: cannot unmarshal object into Go value of type []cmd.dbListEntry'
json: cannot unmarshal object into Go value of type []cmd.dbListEntry
```

It looks as if the API return value in this situation is `{}`, rather than `[]` which seems like it would be expected (and would not generate this error).

**Comment by justinclift** [comment]
Ouch.  Yeah, that does sound like a bug of some sort.  Weird that we've not seen it before though. :smile:

**Comment by justinclift** [comment]
@MKleusberg Any interest in taking a look?

**Comment by MKleusberg** [comment]
@larsks This should be fixed. You don't need a new version of dio for this as the fix happened on the server-side. Do you want to give it a try?

**Comment by larsks** [comment]
Indeed, `dio list` now corrects reports "Cloud 'https://db4s.dbhub.io' has no databases". I ran into a problem with `dio push`, but I'll open that as a separate issue.

**Comment by MKleusberg** [comment]
Awesome! Thanks for checking :smile:
